project:
  type: website
  output-dir: docs

website:
  title: "CSCI 5535 & ECEN 5533 - Fall 2023 - Fundamentals of Programming Languages"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - href: assignments.qmd
        text: Assignments

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc-depth: 1



